import { AppState } from '../shared/types';
import { Store } from './state';
import { YouTubePlayerBridge } from './player';
export class Overlay { readonly root = document.createElement('section'); private meta = document.createElement('div'); private comments = document.createElement('aside'); private description = document.createElement('aside'); constructor(private store: Store, private player: YouTubePlayerBridge, private actions: { next(): void; previous(): void }) { this.root.className = 'ys-root'; this.root.setAttribute('aria-label','YouTube Swipe immersive player'); this.root.innerHTML = `<div class="ys-stage" aria-live="polite"><div class="ys-video-slot"></div><div class="ys-actions"><button data-act="like" aria-label="Like">♥</button><button data-act="dislike" aria-label="Dislike">👍</button><button data-act="comments" aria-label="Open comments">💬</button><button data-act="share" aria-label="Share">↗</button><button data-act="save" aria-label="Save">＋</button></div><div class="ys-meta"></div><div class="ys-controls"><button data-act="play">▶</button><button data-act="back">↑</button><button data-act="next">↓</button><progress value="0" max="1"></progress><button data-act="mute">M</button><button data-act="speed">1x</button><button data-act="pip">PiP</button><button data-act="full">⛶</button></div></div>`; this.meta = this.root.querySelector('.ys-meta')!; this.comments.className = 'ys-panel ys-comments'; this.description.className = 'ys-panel ys-description'; this.root.append(this.comments, this.description); this.root.addEventListener('click', this.handleClick); this.store.subscribe(s => this.render(s)); }
  mount(): void { document.documentElement.classList.add('ys-active-page'); document.body.append(this.root); }
  unmount(): void { document.documentElement.classList.remove('ys-active-page'); this.root.remove(); }
  private render(state: AppState): void { this.root.classList.toggle('ys-reduced-motion', !state.settings.animations); this.root.classList.toggle('ys-dark', state.settings.darkMode); this.root.classList.toggle('ys-comments-hidden', state.settings.hideCommentsButton); this.root.classList.toggle('ys-share-hidden', state.settings.hideShareButton); const m = state.metadata; this.meta.innerHTML = `<button class="ys-channel">@${m.channelName || 'YouTube'}</button><h1>${m.title}</h1><p>${[m.views,m.uploadAge,m.duration].filter(Boolean).join(' • ')}</p><button data-act="description" class="ys-description-button">${m.description ? m.description.slice(0,140) : 'Open description'}</button>`; this.comments.innerHTML = '<button data-act="close-comments">Close</button><div id="ys-comments-host">Use YouTube comments from the original page.</div>'; this.description.innerHTML = `<button data-act="close-description">Close</button><div>${m.description || 'No description available.'}</div>`; }
  private handleClick = (event: Event): void => { const action = (event.target as HTMLElement).closest<HTMLElement>('[data-act]')?.dataset.act; if (!action) return; if (action === 'play') this.player.playPause(); if (action === 'mute') this.player.mute(); if (action === 'full') this.player.fullscreen(this.root); if (action === 'pip') this.player.pip(); if (action === 'speed') this.player.speed(); if (action === 'next') this.actions.next(); if (action === 'back') this.actions.previous(); if (action === 'comments') this.root.classList.add('ys-show-comments'); if (action === 'close-comments') this.root.classList.remove('ys-show-comments'); if (action === 'description') this.root.classList.add('ys-show-description'); if (action === 'close-description') this.root.classList.remove('ys-show-description'); };
}
